package bass

/*
#include "bass.h"
STREAMPROC* _GO_STREAMPROC_DEVICE = STREAMPROC_DEVICE;
STREAMPROC* _GO_STREAMPROC_PUSH = STREAMPROC_PUSH;
STREAMPROC* _GO_STREAMPROC_DUMMY = STREAMPROC_DUMMY;
*/
import "C"

//BASS defines STREAMPROC_PUSH and friends weirdly using #define and Go can't find them
var (
	STREAMPROC_DEVICE = C._GO_STREAMPROC_DEVICE
	STREAMPROC_PUSH = C._GO_STREAMPROC_PUSH
	STREAMPROC_DUMMY = C._GO_STREAMPROC_DUMMY
)